cpu:
    tools:
    - jo
    bin: cpu.sh
    os:
    - kali
    priority: 1
    tags:
    - info
    type: list

df:
    tools:
    - jo
    bin: df.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: table

dmesg:
    tools:
    - jo
    bin: dmesg.sh
    os:
    - kali
    priority: 1
    tags:
    - info
    type: table

info:
    tools:
    - jo
    - jq
    assets:
    - system.json
    bin: info.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    - exploitable
    - top
    type: list

# kernel:
#     bin: kernel.bin
#     os:
#     - kali
#     priority: 1
#     type: list

path:
    tools:
    - jo
    bin: path.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: table

protections:
    tools:
    - jo
    bin: protections.sh
    os:
    - kali
    priority: 1
    tags:
    - info
    type: list