hostnames:
    tools:
    - jo
    bin: hostnames.sh
    os:
    - kali
    - oracle-linux
    priority: 1
    tags:
    - info
    type: list

inetd:
    tools:
    - jo
    bin: inetd.sh
    os:
    - kali
    - endeavouros
    priority: 1
    tags:
    - configs
    type: table

interfaces:
    tools:
    - jo
    bin: interfaces.sh
    os:
    - kali
    - endeavouros
    priority: 1
    tags:
    - info
    type: table

ipv4:
    tools:
    - jo
    bin: ipv4.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 2
    tags:
    - info
    - configs
    type: table

ipv6:
    tools:
    - jo
    bin: ipv6.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 2
    tags:
    - info
    - configs
    type: table

neighbours:
    tools:
    - jo
    bin: neighbours.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: table

ports:
    tools:
    - jo
    - jq
    assets:
    - network.json
    bin: ports.sh
    os:
    - kali
    - oracle-linux
    priority: 1
    tags:
    - info
    - exploitable
    type: table

xinetd:
    tools:
    - jo
    bin: xinetd.sh
    os:
    - kali
    - endeavouros
    priority: 1
    tags:
    - info
    - configs
    type: single

xinetds:
    tools:
    - jo
    bin: xinetds.sh
    os:
    - kali
    - endeavouros
    priority: 1
    tags:
    - info
    - configs
    type: list