compilers:
    tools:
    - jo
    bin: compilers.sh
    os:
    - kali
    priority: 1
    tags:
    - info
    type: table

containers:
    args: docker kubectl aws podman runc rkt ctr
    tools:
    - jo
    bin: check.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: list

keys:
    args: gpg netpgpkeys netpgp openssl keybase
    tools:
    - jo
    bin: check.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: list

network:
    args: nmap curl wget ping telnet nc netcat ncat nc.traditional
    tools:
    - jo
    bin: check.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: list

others:
    args: make gdb base64 socat xterm doas sudo fetch authbind
    tools:
    - jo
    bin: check.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: list

programing:
    args: gcc go g++ java perl php python python2 python3 R ruby rustc
    tools:
    - jo
    assets:
    - kernels.json
    bin: check.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: list

screen:
    tools:
    - jo
    bin: screen.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    - exploitable
    type: list

shells:
    args: sh ash bash dash ksh csh tcsh zsh rc
    tools:
    - jo
    bin: check.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: list

tmux:
    tools:
    - jo
    bin: tmux.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    - exploitable
    type: list