all:
    tools:
    - jo
    - jq
    assets:
    - users.json
    bin: all
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - top
    - info
    type: table

console:
    tools:
    - jo
    bin: console.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: table

current:
    tools:
    - jo
    bin: current.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: single

last:
    tools:
    - jo
    bin: last.sh
    os:
    - kali
    - oracle-linux
    priority: 1
    tags:
    - info
    type: table

last_logon:
    tools:
    - jo
    bin: last_logon.sh
    os:
    - kali
    - oracle-linux
    priority: 1
    tags:
    - info
    type: table

pass_policy:
    tools:
    - jo
    bin: pass_policy.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - configs
    type: list

# pgp:
#     tools:
#     - jo
#     bin: pgp.sh
#     os:
#     - kali
#     priority: 1
#     type: list

# sudo_tokens:
#     tools:
#     - jo
#     bin: sudo_tokens.sh
#     os:
#     - kali
#     - endeavouros
#     priority: 1
#     type: list

superusers:
    tools:
    - jo
    bin: superusers.sh
    os:
    - kali
    - endeavouros
    - oracle-linux
    priority: 1
    tags:
    - info
    type: table