sgid:
    args: g
    tools:
    - jo
    - jq
    assets:
    - files.json
    bin: sxid.sh
    os:
    - kali
    - endeavouros
    priority: 1
    tags:
    - exploitable
    type: table

suid:
    args: u
    tools:
    - jo
    - jq
    assets:
    - files.json
    bin: sxid.sh
    os:
    - kali
    - endeavouros
    priority: 2
    tags:
    - exploitable
    - top
    type: table

writable:
    tools:
    - jo
    - jq
    assets:
    - files.json
    bin: writable.sh
    os:
    - kali
    priority: 3
    tags:
    - exploitable
    type: list